[icons]
name = "awesome"

[icons.overrides]
time = ""
bat_full = "ï‡¦"

[theme]
name = "modern"

[theme.overrides]
separator_bg = "#222D32"
# separator_fg = "#FF00FF"



[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mum}MB"
# format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{utilization} @ {frequency}"

[[block]]
block = "disk_space"
path = "/home/spark"
alias = "/"
info_type = "used"
unit = "GB"
format = "{icon}{used}/{total} {unit}"

[[block]]
block = "time"
interval = 60
format = "%a %F %H:%M"


[[block]]
block = "sound"
max_vol = 200
step_width = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"
